version: '3.8'

services:
  streamlit-app:
    image: chiloh/fang-calculator:latest
    platform: linux/amd64
    ports:
      - "8501:8501"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M